# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceDJApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='usrname',
            new_name='username',
        ),
    ]
