# Generated by Django 2.0.7 on 2018-07-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=32)),
                ('baby_id', models.CharField(max_length=32)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('months', models.IntegerField()),
                ('days', models.IntegerField()),
                ('content_type', models.PositiveSmallIntegerField()),
                ('caption', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_id', models.CharField(max_length=32)),
                ('baby_id', models.CharField(max_length=32)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('content_type', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('src_url', models.CharField(max_length=512)),
                ('months', models.IntegerField()),
                ('days', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete='PROTECT', related_name='event_id', to='timehutBlog.Collection')),
            ],
        ),
    ]
