# Generated by Django 2.0.7 on 2018-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timehutBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='moment',
            name='slug',
            field=models.SlugField(default=123, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
